name: npm test
on:
  workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository    # Name of the step 
        uses: actions/checkout@v3     #Signature of the action
      - name: Install Node.js         
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'       # input Node version
      - name: Install dependencies
        run: npm install

 

  


